import "./globals.css";
import Providers from "../hoc/Providers";
import { Toaster } from "react-hot-toast";
import localFont from "next/font/local";

const poppins = localFont({
	src: "./fonts/Poppins-Regular.ttf",
	variable: "--font-poppins",
	weight: "100 300 400 900",
});
export const metadata = {
	title: "I-EQUIP",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${poppins.className}`}>
				<Providers>
					{children}
					<Toaster />
				</Providers>
			</body>
		</html>
	);
}
