import { Inter, Montserrat } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({
	subsets: ["latin"],
	variable: "--font-Montserrat",
});

export const metadata = {
	title: "PDRRMO",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${inter.className} ${montserrat.className}`}>
				{children}
			</body>
		</html>
	);
}
